* Papers To Read                                                   :noexport:
- [[~/Documents/paper2/papers/tammies_review.pdf]]
  - Major review article
- [[~/Documents/paper2/papers/parkkuo2013.pdf]]
  - Solvent effects on conjugated molecules
  - PPVO molecules can be sythesized with the Horner−Wadsworth−Emmons reaction.
  - Strong dipole-dipole solute-solent interactions responsible for strong solvatochromism
  - Natural Transition orbitals of S_1 are pulled towards end groups with higher electronegativity
  - Emission spectra depends much more on end group and solvent that Absorption sepectra
  - The Stokes shifts in chloroform become even more drastic, varying from 57 nm for H-PPVO to 201 nm for NO 2 -PPVO.
  - We prescribe smaller Stokes shifts as resulting from the dipole−dipole
    (i.e., solvent-PPVO) interactions, controlled by the diffof ground and
    excited state permanent dipoles of the substituted PPVO, as well as solvent
    polarity, constituting the commonly observed solvatochromic effects.
  - In contrast, we attribute the larger Stokes shifts to chromophore aggregation
    where the close-packed PPVOs have strong intermolecular interactions leading
    to the appearance of low-lying weakly emitting intermolecular excited
    states. These aggregated states strongly affect excited states lifetimes and
    PL quantum yield
  - Absorption is dominated by single molecule absorption.
  - Chromophore concentration does not affect spectra's
  - Suggests that the spectroscopic shift is proportional to the weighted sum of g(ε static ) and g(ε optic ).
  - Spectra of Chloroform
    | Concentration | Absorption      | PL               | Description        |
    | e-2 to e-7 M  | 427 nm (2.9 eV) | 632 nm (1.96 ev) | Aggregate Emission |
    | < e-7 M       |                 | 480 nm (2.58 ev) | Single Molecule    |
  - Spectra PPV3-NO2 over solvents e-6 M
    | Solvent    | Absorption       | PL               |
    | Chloroform | ~427 nm (2.9 eV) | 630 nm (1.96 ev) |
    | DMSO       | ~427 nm (2.9 eV) | 500 nm (2.48 ev) |
  - Such strong solvatochromism occurs due to combination of electrostatic
    PPVO-solvent interactions intramolecular charge transfer, and aggregate
    formation in solution.
- [[~/Documents/paper2/papers/sifainbjorgaard2018.pdf]]
  - Sovlent effects on non-adiabatic dynamics of ppvo derivatives
  - Relaxation dependent on solvent
  - PPVO stands for oligo(p-phenylenevinylene)
  - Performs calculations with implicit solvent using CPCM treats the solvent as
    a conductor which simpliﬁes numerical integration of Poisson’s equation at
    the solute−solvent boundary.
  - Trivial Crossing were taken into account
  - In order to guarantee statistical convergence, each ensemble was comprised
    of 635 trajectories.
  - The laser excitations are at 4.30 eV with 0.15 eV line widths which mimic
    the initial excitation for nonadiabatic dynamics into high-energy absorption
    bands.
  - Transitions are independent of molecular conformations across all ground
    state dynamical data,
  - {H, NO 2 } favors charge transfer toward the NO_2.
  - To show relative diﬀerences in excited state energies as a function of ϵ,
    the PESs of each molecule were shifted by their mean ground state energies
    with ϵ = 1.
    | Dielectric | Energy           | Shift    |
    |          1 | 2.79 eV (444 nm) | N.A      |
    |         20 | 2.29 eV (541 nm) | 0.76 eV  |
    |          2 |                  | ~0.03 eV |
    |          5 |                  | ~0.6 eV  |
  - Increasing solvent polarity stabilizes the energy levels and the degree of
    stabilization depends on donor−acceptor groups, where more polar molecules
    (i.e., {H, NO 2 } and {NH 2 , NO 2 }) are further stabilized in more polar
    solvents.
  - PPV3-NO2 has much quicker relazation times than PPV3 Should use for comparison
  - Higher Dielectric dramatically slows relaxation times
  - NA Dynamics:
    - 0.10 fs timestep
    - 0.02 fs quantum timestep
    - langevin at 2 ps$^{-1}$
- [[~/Documents/paper2/papers/wooliu2005.pdf]]
  - Further Studies on solvent effects on PPV groups
  - Understanding how aqueous media influence the linear spectroscopy and TPA
    15-17 of π-conjugated systems is of importance for fully optimizing
    fluorescent tags used in two- photon fluorescence microscopy (TPM) 18 of
    biological samples,such as living cells.
  - Displays a redshift for PL spectra for higher dielectric solvents
  - Found a solvatochromic shift of 636 nm (1.94 eV) - 526 nm (2.35 eV) = -0.31 eV shift at 10^-4 M
- [[~/Documents/paper2/papers/nelsonfernandez2011.pdf]]
  - Tammies Thesis Chapter 4
  - Partial Coupling (PC) and Two State (TS) are described for simplifying coupling equations
  - Coupling simplification is no longer needed due to analytic techniques
  - Classical Path approximation neglect electronic evolution in nuclear dynamics
    - Excited state forces can be found analytically
  - Time constant modeled with 
    \begin{equation}
    f(t) = \frac{Ae^{t/\tau}}{A+e^{t/\tau}} - \frac{A}{1+A}
    \end{equation}
  - friction coefficient 2.0ps$^{-1}$
  - 1080 initial configurations
  - Explains pulse pump simulations
  - 0.1fs and Na = 3 is the standard to compare with previouse work, but S1 population growth is not extremely dependent on those numbers.
  - I can get a good feel for the data using a 2.0 fs timestep. This will help a lot in testing.
  - Higher Langevin Friction Coefficients slow population relaxation
  - Need at least 100 ps to get adequate sampling.
  - In general, the ground state trajectory should be lengthened for larger γ
    val- ues to obtain complete conformational sampling for a given molecular
    system.
  - Our analysis indicates that for all tested parameters, for the given
    molecule, a minimum of 360 trajectories must be computed in order to reach a
    converged result with less than 5% standard deviation. This can be further
    reduced to 2% if 720 trajectories are included.
- [[~/Documents/paper2/papers/nelson2011nonadiabatic.pdf]]
  - Also gives and explanation of computations of excited states
  - Provides formula for analytic gradients
  - Provides formula for analytic energies
  - Provides formula for anlayitc NACRs
    \begin{equation}
      \mathbf{d}_{\alpha\beta} = \frac{ \text{Tr} (F^{(R)}\rho_{\alpha\beta})}{\Omega_\alpha - \Omega_\beta},\alpha \neq \beta
    \end{equation}
    - Provides formula for anlayitc NACTs
    \begin{equation}
      \mathbf{d}_{\alpha\beta} = \frac{ \text{Tr} (F^{(t)}\rho_{\alpha\beta})}{\Omega_\alpha - \Omega_\beta},\alpha \neq \beta
    \end{equation}
  - Excited state energy calculations (O(N$^3$))
  - The TDHF approximation accounts for essential electroniccorrelations
    (electron-hole interactions plus some additional higher-order terms), 68,75
    which is sufficient for a reasonably accurate calculation of UV-visible
    spectra in many extended organic molecular systems. 64
  - However, excited states with a signiﬁcant double excitation character (e.g.,
    A g states in polyacetylene) cannot be represented accu- rately with the
    TDHF and CIS methods.
  - By saving groundstate density, order of magnitude speedup.
  - Lowest excited state of PPV3 is B_u symmetric a 2.74 eV and mAg is 1.72 eV from S1 (~2.0eV)
  - Dynamics:
    - 540 trajectories
  - Measures populations
  - Measures bla
  - Measures dihedral angles
- [[~/Documents/paper2/papers/tammies_thesis_chapter6.pdf]]
  - Shows transfer of energy density of long chained ppv oligimors
  - Following photoexcitation, various nonradiative intraband relaxation
    pathways can lead to a number of complex processe
  - Analytical techniques allow the trajectory to be propagated “on the ﬂy”
    using the complete set of NA coupling terms and remove computational
    bottlenecks in the evaluation of excited-state gradients and NA couplings.
  - The statistical ensemble of trajectories used in surface hopping algorithms
    allows quantum yields (number emitted / number absorbed) and branching ratios (# in particular decay mode/ all decay modes) to be determined
    quantitatively.
  - probability flux
    \begin{equation}
    \dot{a}_{\alpha\alpha} = \sum_{\beta \neq \alpha} b_{\alpha\beta}
    \end{equation}
  - Following a hop, nuclei evolve on the PES of the new state, and energy is
    conserved by rescaling nuclear velocities along the direction of NACR
  - If the nuclear kinetic energy is insufficient to allow a hop to higher
    energy, then the hop is classically forbidden and is rejected.
  - During NA dynamics, state-speciﬁc forces promote electronic and vibrational
    energy funneling to the lowest excited state (as seen in light harvesting
    dendrimers 44−46 ). These ﬁndings discourage any attempt to address
    photodynamics in extended conjugated molecules using the classical-path
    approximation (CPA), 47
  - This simple method is based on the assumption that wavepackets traveling on
    different surfaces should immediately separate in phase space and evolve
    independently. The approach provides qualitative improvement in the
    agreement between classical and quantum systems 29 at no additional
    computational cost and should also allow the coherent nature of transfer
    dynamics on ultrafast time scales to be captured; however this requires
    further study
  - Diagonal elements of TD matrices represent the net change in the electronic
    density distribution induced on an atomic orbital when undergoing a ground
    to excited state transition.
  - TD analysis allows the evolution of the electronic wave function to be
    followed providing a simpliﬁed picture of dynamics that does not rely on
    adiabatic state populations. 28,42,55
  - Failure to detect trivial unavoided crossings will cause adiabatic states,
    deﬁned according to their energy ordering, to be misidentiﬁed leading to
    artifacts in adiabatic state populations. 28,58
  - Pump−probe spectroscopy of polyﬂuorenes revealed fascinating ultrafast (60
    fs) relaxation of the highly excited state, S n , back to the lowest energy
    excited state, S 1 (see Figure 2B for schematic of relevant states). Rivals
    rhodopsin (pigment found in retinal rods)
  - Compares sm (single photon excitation) and sn (two photon exciation (pulse pump))
    - studied on a very long molecule
    - pulse-pump population relaxation significantly faster
    - I cannot use sm results to compare with sn results
    - In particular, owing to the many NA transitions between S n and S 1
      states, momentum is donated to torsional motion causing nuclei to gain
      such high kinetic energy that rapid planarization occurs within 100 fs.
  - Transition density plots show electron-hole distances
- [[~/Documents/paper2/papers/warshellevitt1976.pdf]]
  - Original paper on QM/MM
    - When acid groups ionize, the atoms in it will be plarized, giving induced
      dipoles which interact with the original electrostatic field of the the
      net charge. This interaction always reduces the energy of the system as
      the induced dipoles are always parallel to the electic field inducing
      them.
- [[~/Documents/paper2/papers/walkercrowley2007.pdf]]
  - Implementation of QM/MM in AMBER
  - Split Hamiltonian into three parts
    \begin{equation}
    H = H_{QM} + H_{MM} + H_{QM/MM}
    \end{equation}
  - For semiempirical Hamiltonians we follow the MOPAC programs, and use the
    full electrostatic interactions between the QM charge density (expanded in a
    STO-6G minimal basis set) and the point charges on the MM atoms.
  - However, it is well under-stood that long range electrostatic interactions
    and solvent effects play an important role in the behavior of solvated
    systems.
  - Dealing with covalent bonds
    - Capping Potential (pseudo bond method)
      - Fictitious element is used to cap each bond between the QM and MM regions
    - Hybrid Orbital approach
      - Hybrid or localized frozen orbitals on the QM atom of the QM-MM covalent pair
    - Link Atom approach (SANDER's)
      - In this approach a link atom, which is typically, but not always, a hydrogen, is placed along the bond between the QM and MM region at a suitable distance (1 Å) to satisfy valence requirements.
      - Case 3 is the method currently implemented in Amber 9 where by the link
        atom interacts with both QM and MM atoms and MM link pair atoms are
        excluded from all electrostatic interactions.
    - People running classical force ﬁeld simulations can generally expect that
      the forces used in MD are accurately the gradients of the potential energy
      so that a NVE simulation should yield constant total energy with respect
      to time. However, this has of- ten not been true for QM/MM simulations
      since the QM portion of a QM/MM calculation uses an iterative SCF
      procedure, the forces are only sufﬁciently accurate to conserve energy if
      the difference in energy between subsequent SCF steps is converged to the
      order of around 1 3 10 28 to 1 3 10 29 kcal/mol.
    - that only one value of each constant was used throughout the code and that
      all con- stants and conversion factors are self consistent.
- [[~/Documents/paper2/papers/nelson2013nonadiabatic.pdf]]
  - How tammie solves the decoherence problem
  - the quantum coefficients are evolved coherently along each independent
    nuclear trajectory. That is, the phase factors, or quantum amplitudes, are
    retained.
  - We find that methods that have been used successfully for treating small
    systems do not necessarily translate to large polyatomic systems and their
    success depends on the particular system under study.
  - In principle, decoherence can be included by running a swarm of trajectories
    with the same initial conditions but with a different random number sequence
    to determine hops between adiabatic states
  - Further-more, if one of the divergent wavepackets passes through a region of
    strong coupling multiple times, the wavepacket may undergo yet another
    branching event, compounding the original decoherence problem.
  - In general, the disagreement can be caused by classically forbidden
    transitions or by the divergence of independent trajectories following
    passage through a region of strong coupling.
  - Setting coefficients to unity is justified. This method is physically
    justified: at an avoided crossing a wavepacket will generally branch into
    two subpackets carrying the electronic populations. The subpackets,
    traveling on different surfaces, will separate in phase space and, since
    they are unlikely to in- teract again, the time average of their phase
    differences should be zero.
  - We refer to this scheme as instantaneous decoherence (ID) since it is
    based on the assumption that following a hop, divergent wavepackets will
    instantaneously separate in phase space and should immediately undergo
    independent evolution.
  - Another method that has demonstrated its success in treating decoherence
    29–31 while introducing little additional computational effort is the
    energy-based decoherence correc- tion (EDC) developed by Granucci et al. 17,
    18 in which the coefficients are rescaled at each classical time step.
  - The NA-ESMD model combines the FSSH algorithm, as it is used in the MDQT
    method, 1, 33 with “on the fly” cal- culation of the electronic energies,
    gradients, and nonadiabatic coupling vectors for the excited states using a
    Collective Electronic Oscillator (CEO) package. 34–37 The CEO code is based
    on well-tested semiempirical models combined with the Time-Dependent
    Hartree-Fock (TDHF) or the Configuration Interaction singles (CIS) formalism
    to describe correlated excited states. A detailed description of the CEO
    code and NA-ESMD implementation can be found in Refs.
  - As the classical system continues to relax to lower energy, the quantum
    wavepacket gets “left behind.” That is, the wavepacket remains centered at
    higher energy with respect to the current state with only a small quantum
    probability for the lowest energy state despite that it is the classically
    occupied state.
  - One can imagine that all attempted hops should also be treated as
    decoherence events, regardless of whether the hop is allowed or forbidden
    due to energy constraints.
  - Excitation to S m was performed according to Eq. (10) using a laser centered
    at λ laser = 245 nm and the excited state energies and oscillator strengths
    from the theoretical S1 → Sn absorption spectrum. We found that for the S m
    state, m varied from 8 to 12 due to conformational disorder.
- [[~/Documents/paper2/papers/tully1990.pdf]]
  - Original surface hopping method
  - The importance of tunneling and level quantization effects depends on the
    ratio of the atomic wavelength to the characteristic range of the potential.
    Thus these quantum effects are diminished in systems involving large atomic
    masses and large velocities
  - The method must be practical
  - Trajectories must split into branchers
  - We could determine earch possible path and assign a weight based on its probability
  - We however employ use monte carlo with the decision to hop given probabilities
  - The method should obey energy conservation
  - Thus, transitions should be allowed to occur at any place that the
    electronic coupling is significant. This is a major limitation of the
    conventional surface-hopping technique
  - The probability of a final or intermediate outcome should be obtained simply
    by summing the trajectories that achieve that outcome.
  - The nonadiabatic coupling term is
    \begin{equation}
      \left< \phi_k \left. \right| \frac{\partial \phi_j}{\partial t} \right > = \dot{\mathbf{R}} \cdot \mathbf{d}(\mathbf{R})
    \end{equation}
  - Strongest coupling occurs then change of the wave function overlaps the most
    with the new wave function
  - When attempting to compare classical and quantal dynamics, it is generally
    useful to consider the behavior of a swarm of trajectories rather than an
    individual trajectory. With the present method, each trajectory may make a
    sudden switch of states. But for a swarm of trajectories entering a broad
    region of coupling, some trajectories will switch early, others later, and
    the net result will he a gradual flow of flux from one state to the other.
  - The quantum mechanical results show a smooth dependence on energy, whereas
    the trajectory results show a high frequency oscillation.
- [[~/Documents/paper2/papers/tully2012.pdf]]
  - The adiabatic (Born-Oppenheimer 2 ) PES, E(X), is the 3N-dimensional
    hypersurface of the elec- tronic energy of an N-atom system as a function of
    all nu- clear positions X = {X 1 , X 2 , . . . X N }.
  - Molecular ionization, electron-molecule scattering, and single molecule
    electronics are also controlled by nonadiabatic transitions among electronic
    continuum states.
  - In fact, the exponent in Eq. (1) is often called the Massey parameter; 20
    and serves as a rough indication of nearly adiabatic behavior if it is much
    greater than unity—large energy splitting (2) and low velocity and
    diabatic (completely nonadiabatic) behavior if it is much less than
    unity—small splitting, high velocity.
- [[~/Documents/paper2/papers/weingarcaravelli2012.pdf]]
  - Applies nonadiabatic QM/MM to rhodopsin
  - rhodopsin is the photo-absorbtive molecule in the eye responsible for dim-light vision
  - Use amber
  - Uses CASSCF Complete Active Space Multiconfiguration SCF which has an error
    between excited states of roughly 0.1-0.2eV for small-medium sized molecular
    systems
  - Extensive previous studies have already adopted AM1 and similar
    semiempirical models to investigate excited state properties of
    porphyrin-based molecules.
- [[~/Documents/paper2/papers/zhengfernandez2017.pdf]]
  - Applies NEXMD to chlorophyll
  - Acting as the main antenna in green plants, LHCII is the
  - most abundant LHC in nature.
  - Chla and Chlb
  molecules 13,14 has been studied with the nonadiabatic excited-
  state molecular dynamics (NA-ESMD). 21,22 The ratio of
  simulated relaxation constants in Chla and Chlb monomers
  agreed well with that from ultrafast transient absorption
  spectroscopy.
- [[~/Documents/paper2/papers/tretiaksaxena2002.pdf]]
  - Analyzes bla and torsions effect on bla dynamics
- [[~/Documents/paper2/papers/bjorgaardsheppard2018.pdf]]
  - extended lagrangian applied to nexmd
- [[~/Documents/paper2/papers/cardozoaquino2014.pdf]]
  - Experimental paper on PPV3 with spectra
- [[~/Documents/paper2/papers/martens2016.pdf]]
  - Revisists Mukamels and Tretiak's work
- [[~/Documents/paper2/papers/tammies_open_shell.pdf]]
  - Nexmd applied to openshells
- [[~/Documents/paper2/papers/zhangtretiak_photoisomization.pdf]]
  - Shows Non-Radiative Relaxation of 4‐Styrylquinoline
- [[~/Documents/paper2/papers/martens2020.pdf]]
  - Applies surface hopping using selection by consensus 
- [[~/Documents/paper2/papers/kapral2006.pdf]]
  - Quantum-classical Liouville dynamics
- [[~/Documents/paper2/papers/pandaplasser2020.pdf]]
  - Torsion potential vs length of ppv
- [[~/Documents/paper2/papers/tretiakmukamel2002.pdf]]
  - Long article describing the CEO Method and how to analyze TDM
- [[~/Documents/paper2/papers/tretiakmukamel2002.pdf]]
  - Very mathematically descriptive explanation of CEO applied to TDDFT
- [[~/Documents/paper2/papers/tommasinichernyak2001.pdf]]
  - Closed expressions for nonadiabatic couplings are derived using the
    collective electronic oscillators (CEO) algorithm based on the
    time‐dependent Hartree–Fock equations. Analytic derivatives allow the
    calculation of transition density matrices and potential surfaces at
    arbitrary nuclear geometries using a molecular dynamics trajectory that only
    requires a CEO calculation at a single configuration. © 2001 John Wiley &
    Sons, Inc. Int J Quantum Chem, 2001
- [[~/Documents/paper2/papers/wongwant1998.pdf]]
  - Experiment showing ultrafast planarization of oligimors
- [[~/Documents/paper2/papers/akimovprzhdo2014.pdf]]
  - Reformulates surface hopping to include entanglement and correlation of trajectories
- [[~/Documents/paper2/papers/perkinsherraez2015.pdf]]
  - Applies surface hopping to analyze energy transfer and collisional quenching
- [[~/Documents/paper2/papers/jasperstechmann2002.pdf]]
  - Adds Time Uncertainty to surface hopping 
- [[~/Documents/paper2/papers/jasper2002.pdf]]
  - Adds a new method for treating classically forbidden hops during fewest switches
- ##born1954dynamical##
- ##born1927quantentheorie##
  - Original paper on born openheimer expansion
- [[~/Documents/paper2/papers/subotnikalguire.pdf]]
  - Only approximately diabatic representations exist for polyatomic molecules
- ##joos2013decoherence
  - Book on decoherence
- [[~/Documents/paper2/papers/landrysubotnik2011.pdf]]
  - Why Decoherence can't be ignored
- [[~/Documents/paper2/papers/prezhdorossky1997.pdf]]
  - Questions whether Decoherence should be ignored
- [[~/Documents/paper2/papers/websterschnitker1991.pdf]]
  - Describes a decoherence approach where you project after every time step
- [[~/Documents/paper2/papers/habershonmanolopoulos2013.pdf]]
  - Alternative approach to FSSH & Ehrenfest | Ring-Polymer Molecular Dynamics
- [[~/Documents/paper2/papers/silvathiel2010.pdf]]
  - Benchmarks performance of AM1
- [[~/Documents/paper2/papers/morankelley2003.pdf]]
  - Applies AM1 to chromophores
- [[~/Documents/paper2/papers/tavernellibasile2010.pdf]]
  - Nonadiabatic coupling vectors for excitedstates within time-dependent
    densityfunctional theory in the Tamm–Dancoffapproximation and beyond
- [[~/Documents/paper2/papers/oubellchambers2015.pdf]]
  - We present a complete derivation of derivative couplings between excited
    states in the frame-work of adiabatic time-dependent density functional
    response theory
- [[~/Documents/paper2/papers/marcus1956.pdf]]
  - Theorizes non-adiabatic solvent effects
- [[~/Documents/paper2/papers/martinhay1998.pdf]]
  - Hydrolysis of Ferric Ion in Water and Conformational Equilibrium. Experimental results of solvent effects
- [[~/Documents/paper2/papers/schwartzpeteau1991.pdf]]
  - Investigation of ultra fast excited state intramolecular proton transer of 3-hydroxyflavone
- [[~/Documents/paper2/papers/baylissmcrae1954.pdf]]
  - Early paper describing how solvents could shift spectras
- [[~/Documents/paper2/papers/demoulinaltavilla2018.pdf]]
  - Applies nonadiabatic QM/MM to fine tune retinal photoinduced decay in solutions
- [[~/Documents/paper2/papers/weingartnenov2018.pdf]]
  - COBRAMM 2.0—A software interface for tailoring molecular electronicstructure
    calculations and running nanoscale (QM/MM) simulations
- [[~/Documents/paper2/papers/paterliniferguson1998.pdf]]
  - Using Langevin Equation with verlet integration
- [[~/Documents/paper2/papers/shenaifernandez2016.pdf]]
  - Thermostats should be included in ground state sampline, not much of an effect on namd in large molecules
- [[~/Documents/paper2/papers/barbatti2011.pdf]]
  - Describes trajectory surface hopping
- [[~/Documents/paper2/papers/niklassontymczak2006.pdf]]
  - Time Reversible b-o dynamics
- [[~/Documents/paper2/papers/nelsonnaumov2016.pdf]]
  - Can get a speed up if you ignore high energy states in NACR calculations
- [[~/Documents/paper2/papers/fanghammes1999.pdf]]
  - Describes the problem of trivial unavoided crossings
- [[~/Documents/paper2/papers/wangbeljonne.pdf]]
  - Flexible surface hopping
- [[~/Documents/paper2/papers/tretiakisborn2009.pdf]]
  - Compares iterative procedures such as davidson, lanczoz, arooldi, for RPA iterative solutions
- [[~/Documents/paper2/papers/tretiakchernyak1996.pdf]]
  - Original paper on the CEO approach
- [[~/Documents/paper2/papers/wumalinintretiak2006.pdf]]
  - Nature article on applying naesmd to find exiton-scattering on conjugated polymers
- [[~/Documents/paper2/papers/martin2003.pdf]]
  - Natural transition orbitals
- [[~/Documents/paper2/papers/hernandeznelson2016.pdf]]
  - Describes how to extract energy flow using NEXMD on mulitchromophoric molecules
- [[~/Documents/paper2/papers/nelson2013.pdf]]
  - Tammies paper on Decoherences
- [[~/Documents/paper2/papers/mukameltretiak1997.pdf]]
  - Other original paper on the CEO Approach
- [[~/Documents/paper2/papers/stewart2003.pdf]]
  - Describes how good AM1 heat of formation
- [[~/Documents/paper2/papers/tretiaksaxena2001.pdf]]
  - AM1 with CEO fits well with experiments
- [[~/Documents/paper2/papers/vincentmuuronen2016.pdf]]
  - Describes why na dynamics is important even in reactions with closed shell reactants and products
- [[~/Documents/paper2/papers/katanterenziani2005.pdf]]
  - Light harvesting organic conjugated molecules
- [[~/Documents/paper2/papers/dykstrahennebicq2008.pdf]]
  - Experimental study showing how PPV3 forms conformational subunits defined by conjugations breaks
- [[~/Documents/paper2/papers/nelsonondarse2018.pdf]]
  - Nature paper by Tammie and Dianelys on following coherent exciton-vibratinal dynamics in conjugated systems
- [[~/Documents/paper2/papers/rozzifalke2013.pdf]]
  - Another Nature Article Applying NAMD for light harvesting predictions
- [[~/Documents/paper2/papers/solerroitberg2012.pdf]]
  - Adrian's paper on Unidirection energy tranjufer in conjugated dendrimers using NEXMD following state-specific vibrations
- [[~/Documents/paper2/papers/solernelson2014.pdf]]
  - Further calculations on signatures between nacoulpling and vibrational modes
- [[~/Documents/paper2/papers/bagchi1989.pdf]]
  - Emphasise importance of solvents on dynamics
- [[~/Documents/paper2/papers/sohong2012.pdf]]
  - Experimental paper on PPV3 oligimors and spectras
- [[~/Documents/paper2/papers/sendfurche2009.pdf]]
  - How to analytically calculate NACTs
- [[~/Documents/paper2/papers/nelsonfernandez2014.pdf]]
  - Applying NEXMD to Organic Conjugated Molecules (OCM)
- [[~/Documents/paper2/papers/heckkranz2015.pdf]]
  - QM/MM non-adiabatic charge transport organic semiconductors
- [[~/Documents/paper2/papers/furukawahino.pdf]]  
  - external electric field effects on excited-state intramolecular photon transfer
- [[~/Documents/paper2/papers/balzanicredi2007.pdf]]    
  - A high level overview of photochemical conversion of solar energy
- [[~/Documents/paper2/papers/engelcalhoun.pdf]]
  - Coherence plays an important part in energy transfer processes
- [[~/Documents/paper2/papers/cayecedo-soler2010.pdf]]
  - Study of the light-harvesting bacteria Rhodospirillum
- [[~/Documents/paper2/papers/tavernelli2015.pdf]]
  - Overview of non-adiabatic dynamics
- [[~/Documents/paper2/papers/malonenebgen.pdf]]
  - Newest paper on NEXMD
- [[~/Documents/paper2/papers/christensenkubar2016.pdf]]
  - The best paper on semiemprical methods
- [[~/Documents/paper2/papers/cornilbredas1994.pdf]]
  - Uses AM1 to calculate the optical spectra of PPV-oligomers
- [[~/Documents/paper2/papers/burroughesbradley.pdf]]
  - LEDs using conjugated polymers
    - repone of the system is nonlinear
    - PPV used in light emitting diodes.
- [[~/Documents/paper2/papers/klymchenkoduportail2004.pdf]]
  - Emmission differences due to environments can be exploited for enviornment-sensity fluorescent probes in phospholipid bilayers
- [[~/Documents/paper2/papers/callisburgess1997.pdf]]
  - Postulates that large redshifts in solvents are due to a stark effect.
- [[~/Documents/paper2/papers/marinilosa2010.pdf]]
  - What i solvatochromism
- [[~/Documents/paper2/papers/parkandrews1999.pdf]]
  - Measure the stark effect in protiens
- [[~/Documents/paper2/papers/krieglnienhaus.pdf]]
  - Evidence of strong electric fields in biological systems
- [[~/Documents/paper2/papers/massey1998effect.pdf]]
  - Effect of cholesteryl on photophysics properties
- [[~/Documents/paper2/papers/bondar1999preferential.pdf]]
  - Cholesterol's effect on the fluorescents
- [[~/Documents/paper2/papers/spano2000emission.pdf]]
  - Cholesterol's effect on the fluorescents
- [[~/Documents/paper2/papers/granstrom1998laminated.pdf]]
  - Laminated Fabrication process  using PPV. 
  - Solvent include chloroform and toluene
- [[~/Documents/paper2/papers/cao1999improved.pdf]]
  - singlet bound states are formed with higher probabilities in PPV3
- [[~/Documents/paper2/papers/sirringhaus2000high.pdf]]
  - using an inkjet to cheaply produce PPV molecules for organic transistors.
- [[~/Documents/paper2/papers/bredas2004charge.pdf]]
  - charge and energy transfers in pi ocnjugated oligomers and polymers using a molecular picture
- [[~/Documents/paper2/papers/bredas2009excitons.pdf]]
  - Describes the exciton behavior over PPV
- [[~/Documents/paper2/papers/collini2009coherent.pdf]]
  - Shows that coherency can occur in PPV at roughly 250fs
- [[~/Documents/paper2/papers/chiang1977electrical.pdf]]
  - showed high conductivity during a redox chemical experiment
- [[~/Documents/paper2/papers/brown1992poly.pdf]]
  - first organic conjugated polymer LED using PPV
- [[~/Documents/paper2/papers/bredas2009molecular.pdf]]
  - Explanation of how light havesting works in organic semiconductors acceptor donor 
  - Frenkeltype exciton
  - exciton binding energy is typically large ~ 0.5eV much greater than the milieV in inorganic semiconductors.
  - absorption in inorganic semiconductors immediately lead to free electron and hole carriers.
- [[~/Documents/paper2/papers/soos1993band.pdf]]
  - Show that the S1 state to be two photon allowd for strong correlation and dipole allowd with weak correlations.
- [[~/Documents/paper2/papers/fernandez2012identification.pdf]]
  - Paper on trivial crossings
  - According to the  von Neumann-Wigner theorem,  energy  between electronic states with the same symmetry in polyatomic molecules may cross unavoidedly.
- [[~/Documents/paper2/papers/hull1996runge.pdf]]
  - Review paper on the Runge-Kutta numerical integration
- [[~/Documents/paper2/papers/hammes1994proton.pdf]]
  - Paper describing how to perfrom molecular dynamics with quantum transitions
- [[~/Documents/paper2/papers/bredas1994influence.pdf]]
  - Paper describing how to substituents could change the properties of PPV
  - Shows that the energies of the och3 derivatives have lower energies than ppv alone
  -  The workfunctions of the LEDs are Calcium and Aluminum
- [[~/Documents/paper2/papers/partridge1996high.pdf]]
   - Describes how a sensor of could be created using Conjugated Organic Polymers
- [[~/Documents/paper2/papers/friend1997electronic.pdf]]
  - Another papers on how PPV can be used for LEDs
- [[~/Documents/paper2/papers/history_of_photochemistry.pdf]]
  - Paper on the history of photochemistry
- [[~/Documents/paper2/papers/priestley1772observations.pdf]]
  - Super old paper describing the discovery of oxidation
- [[~/Documents/paper2/papers/pope193electroluminescence.pdf]]
  - Paper showing electroluminescence in organic crystal
**  Papers to read for chapter 6 from sebastian
- [[~/Documents/paper2/papers/miller2002ultrafast.pdf]]
- [[~/Documents/paper2/papers/lee201electronic.pdf]]
- [[~/Documents/paper2/papers/robotham2013ultrafast.pdf]]
- [[~/Documents/paper2/papers/philip2020directing.pdf]]
- [[~/Documents/paper2/papers/wallin2010state.pdf]]




